# Generated by Django 3.0.7 on 2021-02-13 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryName', models.CharField(max_length=200)),
                ('categoryId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogTitle', models.CharField(max_length=200)),
                ('blogId', models.IntegerField()),
                ('blogContent', models.TextField(max_length=1000)),
                ('blogCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Categories')),
            ],
        ),
    ]
